[package]
name = "core"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-skiplist = "0.1"
bytes = "1.6.1"
ouroboros = "0.18.4"
crc32fast = "1.4.2"
farmhash = "=1.1.5"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.122"

