[package]
name = "db"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-skiplist = "0.1"
storage = {path = "../storage" }
shared = {path = "../shared" }
rand = "0.9.0-alpha.2"
bytes = "1.6.1"
clap = { version = "4.5.17", features = ["derive"] }
