[package]
name = "shared"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam-skiplist = "0.1"
serde_json = "1.0.122"
farmhash = "=1.1.5"
bytes = "1.6.1"
serde = { version = "1.0.209", features = ["derive"] }
